spring:
  application:
    name:  sc-gateway
  cloud:
    gateway:
      discovery:
        locator:
          #          enabled: true  #开启从注册中心动态创建路由，利用微服务的名称进行路由  可以网关/服务名/接口路径访问
          lower-case-service-id: true  #将服务名转化为小写
          enabled: false  #想通过指端路由来跳转，就关闭
      #当满足多路由的断言时，是从上往下执行第一个
      routes:
        - id: path_rote
          uri: lb://eureka-client
          predicates:
            - Path=/demo/**
          filters:
            - StripPrefix=1
            - name: RequestRateLimiter
              args:
                key-resolver: '#{@hostAddrKeyResolver}'        #限流的键   bean对象名称  使用spEL，#{@beanName}从spring容器中获取
                redis-rate-limiter.replenishRate: 1        #令牌桶的每秒填充速率
                redis-rate-limiter.burstCapacity: 1        #令牌桶总容量
        - id: after_route
          uri: lb://eureka-client     #lb: 负载均衡
          predicates:
            - After=2021-01-01T17:42:47.789-07:00[America/Denver]
        #            - Path=/demo/**    可以添加多中断言过滤条件
        #          filters:
        #            - StripPrefix=1
  redis:
    host: localhost
    port: 6379
    database: 0
eureka:
  instance:
    lease-expiration-duration-in-seconds: 10  #没有心跳的淘汰时间 10s    默认90s
    lease-renewal-interval-in-seconds: 5  #心跳间隔 5秒   默认30s
    #在eureka中显示ip地址
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${server.port}

  client:
    registerWithEureka: true
    fetchRegistry: true
    registry-fetch-interval-seconds: 5  #定时刷新本地缓存时间
    service-url:
      defaultZone: http://localhost:8761/eureka/
