
server:
  port: 8761
spring:
  application:
    name: govern-center

eureka:
  client:
    register-with-eureka: false #服务注册,是否将自己注册到Eureka服务中
    fetch-registry: false #服务发现,是否从Eureka中获取注册信息
    service-url:  #Eureka客户端与Eureka服务端的交互地址,高可用状态配对方的地址,单击状态配自己的地址(如果不配置,默认本机8761端口)
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
    enable-self-preservation: false #是否开启自我保护模式
    eviction-interval-timer-in-ms: 5000 #服务注册表清理间隔(单位:毫秒,默认是60*1000)(主动失效检测间隔)
    use-read-only-response-cache: false
  instance:
    hostname: localhost
    lease-expiration-duration-in-seconds: 10 #没有心跳的淘汰时间  默认90s  这一行可以不配置（这里和客户端一样）

